# Generated by Django 6.0.4 on 2026-06-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
