# Generated by Django 6.0.4 on 2026-06-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_no_overlap_constraint'),
        ('venues', '0004_alter_venue_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='max_attendees',
            field=models.PositiveIntegerField(default=20, help_text='Auto-approve if attendee_count is at or below this value.'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='max_duration_hours',
            field=models.FloatField(default=2.0, help_text='Auto-approve if the booking duration is at or below this many hours.'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='min_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Auto-approve only when the booking is made this far in advance.'),
        ),
        migrations.AlterField(
            model_name='autoapprovalrule',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply this rule to every venue.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_approval_rules', to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='termdate',
            name='name',
            field=models.CharField(help_text='e.g. "Winter Break 2026" or "Reading Week — Spring"', max_length=200),
        ),
        migrations.AlterField(
            model_name='termdate',
            name='skip_in_recurrence',
            field=models.BooleanField(default=True, help_text='Recurring booking series will skip dates inside this period.'),
        ),
    ]
