# Generated by Django 6.0.4 on 2026-06-21 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_checked_in_by_booking_key_returned_at'),
        ('venues', '0004_alter_venue_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyHandout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, default='', max_length=150)),
                ('holder_role', models.CharField(choices=[('CLEANER', 'Cleaner'), ('STAFF', 'Staff'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('room_label', models.CharField(blank=True, default='', max_length=150)),
                ('purpose', models.CharField(choices=[('CLEANING', 'Cleaning'), ('OFFICE', 'Office access'), ('MAINTENANCE', 'Maintenance'), ('EVENT', 'Event setup'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('handed_out_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('handed_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys_handed_out', to=settings.AUTH_USER_MODEL)),
                ('holder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys_held', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys_received_back', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_handouts', to='venues.venue')),
            ],
            options={
                'ordering': ['-handed_out_at'],
            },
        ),
    ]
