# Generated by Django 6.0.4 on 2026-07-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_keyhandout'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_full_day',
            field=models.BooleanField(default=False, help_text='Booked for the whole operating day (start/end still store the actual hours).'),
        ),
    ]
