# Generated by Django 6.0.4 on 2026-06-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='venue',
            name='building',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='min_notice_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(blank=True, default='', help_text='e.g. Lecture hall, Studio, Lab, Seminar room, Outdoor, Music, Sports', max_length=40),
        ),
    ]
