# Generated by Django 6.0.4 on 2026-06-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='access',
            field=models.CharField(choices=[('both', 'Staff and students'), ('staff', 'Staff only'), ('student', 'Students only'), ('none', 'Not bookable (hidden)')], default='both', max_length=20),
        ),
    ]
