# Generated by Django 6.0.4 on 2026-07-08 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venue_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='requires_vc_approval',
            field=models.BooleanField(default=False, help_text='Bookings for this venue may only be approved or declined by the VC role.'),
        ),
        migrations.CreateModel(
            name='VenuePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_label', models.CharField(blank=True, default='', help_text='e.g. Caretaker, AV Technician', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_venues', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='venues.venue')),
            ],
            options={
                'ordering': ['venue__name', 'role_label'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'user'), name='unique_personnel_per_venue')],
            },
        ),
    ]
