# Generated by Django 6.0.4 on 2026-07-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mfa_enabled_user_mfa_secret_mfabackupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloweddomain',
            name='default_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('VC', 'Vice-Chancellor'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrolllink',
            name='default_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('VC', 'Vice-Chancellor'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('VC', 'Vice-Chancellor'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
